exports.bosses = {
    17632: "Skorvald",
    17949: "Artsariiv",
    17759: "Arkk",
    17021: "MAMA",
    17028: "Siax",
    16948: "Ensolyss",
    23254: "Disco Pogo",
}

exports.instabDict = {
    1: "Adrenaline Rush",
    2: "Afflicted",
    3: "Boon Overload",
    4: "Flux Bomb",
    5: "Fractal Vindicators",
    6: "Frailty",
    7: "Hamstrung",
    8: "Last Laugh",
    9: "Mists Convergence",
    10: "No Pain, No Gain",
    11: "Outflanked",
    12: "Social Awkwardness",
    13: "Stick Together",
    14: "Sugar Rush",
    15: "Toxic Trail",
    16: "Vengeance",
    17: "We Bleed Fire",
    18: "Toxic Sickness",
};

exports.fractalDict = {
    A: "Aetherblade",
    B: "Aquatic Ruins",
    C: "Captain Mai Trin",
    D: "Chaos Isles",
    E: "Cliffside",
    F: "Deepstone",
    G: "Molten Boss",
    H: "Molten Furnace",
    I: "Nightmare",
    J: "Shattered Observatory",
    K: "Sirens Reef",
    L: "Snowblind",
    M: "Solid Ocean",
    N: "Swampland",
    O: "Thaumnova Reactor",
    P: "Twilight Oasis",
    Q: "Uncategorized",
    R: "Underground Facility",
    S: "Urban Battleground",
    T: "Volcanic",
    U: "Sunqua Peak",
};